apiVersion: pingcap.com/v1alpha1
kind: IoChaos
metadata:
  name: tiflash-io-delay
  namespace: tiflash-chaos
spec:
  action: delay
  mode: one
  duration: "400s"
  configName: "chaosfs-tiflash"
  path: ""
  selector:
    namespaces:
      - tiflash-test2
    labelSelectors:
      "app": "tiflash"
  layer: "fs"
  delay: "10ms"
  scheduler:
    cron: "@every 10m"
