apiVersion: pingcap.com/v1alpha1
kind: NetworkChaos
metadata:
  name: pd-tiflash-p
  namespace: tiflash-chaos-testing
spec:
  action: partition
  mode: all
  selector:
    namespaces:
      - tiflash-test2
    labelSelectors:
      "app.kubernetes.io/component": "pd"
  direction: to
  target:
    selector:
      namespaces:
        - tiflash-test2
      labelSelectors:
        "app": "tiflash"
    mode: all
  duration: "20s"
  scheduler:
    cron: "@every 40s"