# 0. The tiflash image needs to be pushed to a Docker registry, and the following `image` field need to be adjusted to the registry address.
# 1. helm install pingcap/tidb-cluster --name=${TIDB_CLUSTER_NAME} --namespace=${MY-NAMESPACE} --version=v1.0.2 --set pd.image=tiflash,tikv.image=tiflash,tidb.image=tiflash
# 2. Replace the following TIDB_CLUSTER_NAME with the real tidb cluster name.
# 3. kubectl apply -f tiflash.yaml
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: rngine
spec:
  selector:
    matchLabels:
      app: rngine
  serviceName: rngine
  replicas: 3
  template:
    metadata:
      labels:
        app: rngine
    spec:
      initContainers:
      - name: init-rngine
        image: hub.pingcap.net/tiflash/kube-test-rngine
        command:
        - bash
        - "-c"
        - |
          set -ex
          [[ `hostname` =~ -([0-9]+)$ ]] || exit 1
          ordinal=${BASH_REMATCH[1]}
          sed s/{pod_num}/${ordinal}/g /etc/rngine_templ/rngine_templ.toml > /data/rngine.toml
      volumeMounts:
      - name: data3
        mountPath: /data
      containers:
      - name: rngine
        image: hub.pingcap.net/tiflash/kube-test-rngine
        command:
        - /tikv-server-rngine
        - --addr=0.0.0.0:20170
        - --data-dir=/data/rngine
        - --pd=tiflash-test-cluster-pd.tiflash-test.svc:2379
        - --config=/data/rngine.toml
        env:
        - name: MY_POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: MY_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        volumeMounts:
        - name: data
          mountPath: /data
        - name: config_rngine
          mountPath: /etc/rngine_templ
      volumes:
      - name: config_rngine
        configMap:
          name: rngine
          items:
          - key: rngine_templ.toml
            path: rngine_templ.toml
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "local-storage"
      resources:
        requests:
          storage: 10Gi
---
apiVersion: v1
kind: Service
metadata:
  name: rngine
  labels:
    app: rngine
spec:
  ports:
  - port: 20170
  clusterIP: None
  selector:
    app: rngine
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: rngine
data:
  rngine_templ.toml: |
    [readpool.storage]
    [readpool.coprocessor]
    [server]
    labels = { "engine" = "tiflash", "tiflash_http_port" = "8123" }
    # TODO: does tiflash support multiple instances, how should we configure the engine-addr if there are multiple tiflash instance
    # Replace the MY_NAMESPACE with the real namespace
    engine-addr = "tiflash-{pod_num}.tiflash.default.svc:3930" # tics address
    advertise-addr = "rngine-{pod_num}.rngine.default.svc:20170"
    [storage]
    [pd]
    # This section will be overwritten by command line parameters
    [metric]
    #address = "172.16.30.31:9531"
    #interval = "15s"
    #job = "tikv"
    [raftstore]
    raftdb-path = ""
    sync-log = true
    max-leader-missing-duration = "22s"
    abnormal-leader-missing-duration = "21s"
    peer-stale-state-check-interval = "20s"
    hibernate-regions = false
    [coprocessor]
    [rocksdb]
    wal-dir = ""
    [rocksdb.defaultcf]
    block-cache-size = "10GB"
    [rocksdb.lockcf]
    block-cache-size = "4GB"
    [rocksdb.writecf]
    block-cache-size = "4GB"
    [raftdb]
    [raftdb.defaultcf]
    block-cache-size = "1GB"
    [security]
    ca-path = ""
    cert-path = ""
    key-path = ""
    [import]
